#!/bin/bash -e
# Copyright (c) 2018 Marco Stolze (alias mcpride)

ORG_PATH="github.com/mcpride"
REPO_PATH="${ORG_PATH}/giotamonic"
BUILD_TAG="${TRAVIS_TAG:-$(git describe --all | sed -e's/.*\///g')}"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

GOARCH=amd64 GOOS=linux go build -o bin/giotamonic-${BUILD_TAG}-linux-amd64 ${REPO_PATH}
GOARCH=amd64 GOOS=darwin go build -o bin/giotamonic-${BUILD_TAG}-darwin-amd64 ${REPO_PATH}
GOARCH=amd64 GOOS=windows go build -o bin/giotamonic-${BUILD_TAG}-windows-amd64 ${REPO_PATH}
