#!/bin/bash -e
# Copyright (c) 2018 Marco Stolze (alias mcpride)

source ./build

if [ -z "$PKG" ]; then
    PKG="iota_mnemonic"
fi

export BUILD_TAG="${TRAVIS_TAG:-$(git describe --all | sed -e's/.*\///g')}"

# Unit tests
echo
for mod in $PKG; do
  mod_path=$REPO_PATH/$mod
  go test -i $mod_path
done
